login_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^info$', views.info, name='info'),
    url(r'^info/(?P<pk>[a-zA-Z0-9]+)', views.UserInfoDetailView.as_view(), name='detail'),
]

schedule/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('login_app.urls')),
    url(r'^login/', include('login_app.urls')),
    url(r'^todotask/', include('todotask.urls')),
    url(r'^admin/', admin.site.urls),
]

todotask/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<username>[a-zA-Z0-9]+)/set', views.set_task, name='set'),
    url(r'^(?P<username>[a-zA-Z0-9]+)/modify', views.modify_task, name='modify'),
    url(r'^todotask', views.todotask, name='todo'),
    url(r'^(?P<username>[a-zA-Z0-9]+)', views.todoView, name='todotask'),
]

login_app/models.py
from django.db import models

class User_info(models.Model):
    username = models.CharField(max_length=16, primary_key=True)
    password = models.CharField(max_length=32)
    email = models.CharField(max_length=32, default='')
    birth = models.DateTimeField('Birthday', default='1990-1-1')
    def __str__(self):
        return self.username

todotask/models.py
from django.db import models

class ToDoTasks(models.Model):
    username = models.CharField(max_length=16)
    index = models.IntegerField(default=0, null=False)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=1000)
    note = models.CharField(max_length=100, default='', null=True, blank=True)
    done = models.BooleanField(default=False)
    def __str__(self):
        return self.title

login_app/forms.py
from django import forms

class User_form(forms.Form):
    username = forms.CharField(max_length=16)
    email = forms.CharField(max_length=32)
    password = forms.CharField(max_length=32)
    birth = forms.DateTimeField()

login_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import generic
from .models import User_info
from .forms import User_form

def login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = User_info.objects.filter(username=username).values()
        if not user:
            raise Http404('User name {} not found'.format(username))
        else:
            #Check password
            if user[0].get('password') == password:
                return HttpResponseRedirect('/todotask/{}'.format(username))
            else:
                return HttpResponse('Password Error')
    else:
        return render(request, 'login_app/login.html')

def register(request):
    return render(request, 'login_app/register.html')

def info(request):
    form = User_form(request.POST)
    if form.is_valid():
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        birthday = request.POST.get('birth')
    user_info = User_info(username=username, password=password, email=email, birth=birthday)
    user_info.save()
    return HttpResponseRedirect('info/{}'.format(username))

class UserInfoDetailView(generic.DetailView):
    model = User_info
    template_name = 'login_app/detail.html'
    def get_context_data(self, **kwargs):
        context = super(UserInfoDetailView, self).get_context_data(**kwargs)
        return context

todotask/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView as LV
from .models import ToDoTasks

def todoView(request, username):
    task_list = ToDoTasks.objects.filter(username=username).values()
    template_name = 'todotask/show_task.html'
    context = {
        'task_list': task_list,
        'username': username,
    }
    return render(request, template_name, context)
    
def todotask(request):
    if request.POST:
        username = 'houlu'#request.POST.get('username')
        title = request.POST.get('title')
        content = request.POST.get('content')
        todo = ToDoTasks(username=username, title=title, content=content)
        todo.save()
        return HttpResponseRedirect(username)
    return HttpResponse('hello')

def set_task(request, username):
    return render(request, 'todotask/set_task.html')

def modify_task(request, username):
    if request.POST:
        print(request.POST)
    return HttpResponseRedirect(username)

login_app/templates/login_app/detail.html
<h1>User information</h1>
<h2>{{ object.username }}</h2>

<p>{{ object.email }}</p>
<br />
<p>{{ object.birthday|date }}</p>

login_app/templates/login_app/login.html
<script type="text/javascript">
function httpGet(url) {
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.onreadystatechange = function () {
        if (xmlHttp.readyState === 4 && xmlHttp.status === 200) {
            document.write(xmlHttp.responseText);
        }
    }
    xmlHttp.open("GET", url, true);
    xmlHttp.send(null);
}
</script>
<h1>Login system</h1>

<form action="" method="post">
{% csrf_token %}
    Username: <input type="text" name="username" id="username" />
    <br />
    Password: <input type="password" name="password" id="password" />
    <br />
<input type="submit" value="submit" />
<input type="button" value="register" onclick="httpGet('register')">
</form>

login_app/templates/login_app/register.html
<h1>User register</h1>
Please fill your information

<form action="info" method="post">
{% csrf_token %}
    Username: <input type="text" name="username" id="username" />
    <br />
    Password: <input type="text" name="password" id="password" />
    <br />
    Email address: <input type="email" name="email" id="email" />
    <br />
    Birthday: <input type="date" name="birth" id="birth" />
<input type="submit" value="Submit" />
</form>

login_app/templates/login_app/user_info.html
{% if user_info_list %}
    <ul>
    {% for user in user_info_list %}
        <li><a href="/login_app/{{ user.id }}/">{{ user.username }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p> No users are available </p>
{% endif %}

todotask/templates/todotask/set_task.html
<h1>Set task</h1>

<form action='todotask' method='POST'>
{% csrf_token %}
    title: <input type='text' name='title' id='title' />
    content: <input type='text' name='content' id='content' />
<input type='submit' value='Submit'>
</form>

todotask/templates/todotask/show_task.html
<h1>Your task</h1>
<h2>{{ username }}</h2>

<table border=1>
{% for task in task_list %}
    <tr>
        <th>index</th>
        <th>title</th>
        <th>content</th>
        <th>state</th>
        <th>modify</th>
    </tr>
    <tr>
        <td>{{ task.index }}</td>
        <td>{{ task.title }}</td>
        <td>{{ task.content }}</td>
        {% if task.done %}
            <td bgcolor='blue'>DONE</td>
            <td><form action='houlu/modify' method='post'>
                {% csrf_token %}
                <button type='submit' name='change'>UNDONE</button>
            </form></td>
        {% else %}
            <td bgcolor='red'>UNDONE</td>
            <td><form action='houlu/modify' method='post'>
                {% csrf_token %}
                <button type='submit' name='change'>DONE</button>
            </form></td>
        {% endif %}
    </tr>
{% endfor %}
</table>

<form action="set" method="get">
    <button type='submit'>set</button>
</form>